{% set name = "stimuli" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stimuli-{{ version }}.tar.gz
  sha256: daf1ed741a34aba0796d772d25289735a99700f30c2d1cb520498aa8e839ac53

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - stimuli = stimuli.commands.main:run

requirements:
  host:
    - pip
    - python >=3.11
    - setuptools >=64.0.0
  run:
    - click >=8.1
    - matplotlib-base
    - numpy >=1.23
    - packaging
    - psutil
    - pyserial
    - python >=3.11
    - python-sounddevice
    - scipy

test:
  imports:
    - stimuli
  requires:
    - pip
  commands:
    - pip check
    - stimuli sys-info --help

about:
  home: https://mscheltienne.github.io/stimuli/
  summary: Accurate aditory stimuli that do not require PsychoPy.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/mscheltienne/stimuli

extra:
  recipe-maintainers:
    - mscheltienne
