{% set name = "stimuli" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stimuli-{{ version }}.tar.gz
  sha256: 2a8aed3ae32429cd7b7d4ed12008f438b47f2e530ba5b8b7ea10be0868185f22

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - stimuli-sys_info = stimuli.commands.sys_info:run
    - stimuli_cross = stimuli.commands.stimuli_cross:run

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools >=64.0.0
  run:
    - matplotlib-base
    - numpy >=1.21
    - opencv
    - packaging
    - psutil
    - python >=3.10
    - python-sounddevice
    - scipy
    - screeninfo

test:
  imports:
    - stimuli
  requires:
    - pip
  commands:
    - pip check
    - stimuli-sys_info --help
    - stimuli_cross --help

about:
  home: https://mscheltienne.github.io/simple-stimuli/dev/index.html
  summary: Simple auditory and visual stimuli that do not require PsychoPy.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/mscheltienne/simple-stimuli

extra:
  recipe-maintainers:
    - mscheltienne
